language: node_js
node_js:
  - "6"
cache:
  directories:
    "node_modules"
sudo: false
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
install:
  - npm install
script:
  - npm run lint
  - npm run test
