language: node_js
node_js:
  - "7"
cache:
  yarn: true
  directories:
    "node_modules"
before_script:
  - yarn run build
  - sleep 15
  - mongo aprendfy-test --eval 'db.addUser("travis", "test");'
after_script:
  - yarn run test
services: 
  - mongodb
